/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./../src/layouts/AuthLayout/index.vue')['default']
    BaseLayout: typeof import('./../src/layouts/BaseLayout/index.vue')['default']
    DataTableLayout: typeof import('./../src/layouts/DataTableLayout/index.vue')['default']
    DpBarChart: typeof import('./../src/charts/DpBarChart/index.vue')['default']
    DpDevMenuFab: typeof import('./../src/components/DpDevMenuFab/index.vue')['default']
    DpGlobalLoading: typeof import('./../src/components/DpGlobalLoading/index.vue')['default']
    DpHTMLPrinter: typeof import('./../src/components/DpHTMLPrinter/index.vue')['default']
    DpLineChart: typeof import('./../src/charts/DpLineChart/index.vue')['default']
    DpNumberAnimation: typeof import('./../src/components/DpNumberAnimation/index.vue')['default']
    DpPieChart: typeof import('./../src/charts/DpPieChart/index.vue')['default']
    DpReportUserTrafficProvider: typeof import('./../src/components/DpReportUserTrafficProvider/index.vue')['default']
    DpTimeline: typeof import('./../src/components/DpTimeline/index.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
